enable_modelarts: 0

# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
output_path: "/cache/train"

# train datasets
dataset_path: '/PATH_TO_CODE/dataset/imagenet/train'
train_image_size: 224
interpolation: 'BILINEAR'
crop_min: 0.05
batch_size: 64
train_num_workers: 14

# eval datasets
eval_path: '/PATH_TO_CODE/dataset/imagenet/val'
eval_image_size: 224
eval_batch_size: 64
eval_interval: 1
eval_offset: -1
eval_num_workers: 12

# network
backbone: 'dgmn2_tiny'
class_num: 1001
dgmn2_config_path: 'src.dgmn2.DGMN2Config'
pretrained: ''

# lr
lr_decay_mode: 'cosine'
lr_init: 0.0
lr_max: 0.0006
lr_min: 0.00005
max_epoch: 300
warmup_epochs: 5

# optimizer
opt: 'adamw'
beta1: 0.9
beta2: 0.999
weight_decay: 0.05
no_weight_decay_filter: "beta,bias"
gc_flag: 0

# loss
loss_scale: 1024
use_label_smooth: 1
label_smooth_factor: 0.1
mixup: 0.2
autoaugment: 1
loss_name: "ce_smooth_mixup"

# ckpt
save_checkpoint: 1
save_checkpoint_epochs: 8
keep_checkpoint_max: 3
save_checkpoint_path: './outputs'

# profiler
open_profiler: 0

# train
context_mode: 0
device_target: "Ascend"
amp_level: "O3"
run_distribute: 0
